apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-huhh
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-huhh@sha256:6dd7a7899b7fda0bcd82a42a7650a6a6cc09e26034cc2c688c019c134fd64f71
        name: my-nodejs
        resources: {}
status: {}
